http:
  port: 3002
log:
  format: "json"
  level: "trace"
db:
  host: localhost
  port: 5432
  user: app
  password: change_me
  name: app
  sslMode: disable
  timezone: UTC
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: 10h
  connMaxIdleTime: 15m
  logLevel: warn
jwt:
  secret: your-jwt-secret
services:
  general:
    baseURL: http://localhost:3002
    apiKey: Entwt4/uwQtnD2LqMdho4cPTmFEkGAzBytS4UsO0f8g=
