http:
  port: 3002
log:
  format: "json"
  level: "trace"
jwt:
  secret: your-jwt-secret
services:
  general:
    baseURL: http://localhost:3002
    apiKey: Entwt4/uwQtnD2LqMdho4cPTmFEkGAzBytS4UsO0f8g=
